version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-image-ai-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - USE_WEBHOOK=false
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PHOTOROOM_API_KEY=${PHOTOROOM_API_KEY}
      - REMOVEBG_API_KEY=${REMOVEBG_API_KEY}
      - MAX_REQUESTS_PER_USER=10
      - RATE_LIMIT_WINDOW=3600
      - MAX_FILE_SIZE=20971520
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs: